function row(k, v) {
  return `| ${k} | ${v} |`;
}

export function renderProjectMd(cfg) {
  const { project, runtime, commands, devserver, roles } = cfg;
  const enabledRoles = Object.entries(roles)
    .filter(([, on]) => on)
    .map(([r]) => r);

  const cmdRows = Object.entries(commands)
    .filter(([, v]) => v)
    .map(([k, v]) => row("`" + k + "`", "`" + v + "`"))
    .join("\n");

  const sources = cfg.sources_of_truth
    .map((s) => `| \`${s.path}\` | ${s.what} | ${s.how} |`)
    .join("\n");

  const gotchas = cfg.gotchas.length
    ? cfg.gotchas.map((g) => `- ${g}`).join("\n")
    : "- (поки немає — додай у `team.config.yaml`)";

  return `# Project context — ${project.name}

> ГЕНЕРОВАНО з \`team.config.yaml\`. Не редагуй вручну — зміни конфіг і запусти \`agentcrew sync\`.
> Кожна роль читає цей файл на bootstrap ПІСЛЯ \`protocol.md\`.

## Базове
- **Назва проєкту:** ${project.name}
- **Корінь:** \`${project.root}\`
- **Мова спілкування агентів:** ${project.language}
- **Префікс tmux-сесій:** \`${project.name}-<role>\` (напр. \`${project.name}-teamlead\`, \`${project.name}-dev\`)
- **Активні ролі:** ${enabledRoles.join(", ")}

## Стек / рантайм
- **Package manager:** ${runtime.package_manager}
- **Exec prefix:** \`${runtime.exec_prefix}\`

## Команди
| Дія | Команда |
|---|---|
${cmdRows}

## Dev-сервер
- **Порт:** ${devserver.port}
- **Health URL:** ${devserver.health_url}

## Quality standard (бібла для code review)
${cfg.quality_standard ? "`" + cfg.quality_standard + "`" : "`.agent-crew/knowledge/principles.md` (генерик — допили під проєкт)"}

## Джерела правди
| Шлях | Що містить | Як читати |
|---|---|---|
${sources}

## Project gotchas
${gotchas}

## Memory
- \`${cfg.memory.path}\`
`;
}

export function renderBinScripts(cfg) {
  const prefix = cfg.project.name;
  const port = cfg.devserver.port;
  const health = cfg.devserver.health_url;
  const dev = cfg.commands.dev || "echo 'no dev command configured' && sleep infinity";
  const pm = cfg.runtime.package_manager;

  const bootstrap =
    "Прочитай повністю .agent-crew/agents/teamlead/CLAUDE.md і працюй за цією роллю. " +
    "Далі прочитай .agent-crew/agents/_shared/protocol.md і .agent-crew/agents/_shared/project.md. " +
    "Якщо .agent-crew/knowledge/onboarding.md ще не існує — спершу зроби self-onboarding: " +
    "досліди проєкт і напиши onboarding.md + architecture.md у .agent-crew/knowledge/, " +
    "покажи мені summary і спитай, над чим працюємо. Інакше — підніми dev/qa/devserver і чекай задачі.";

  const launch = `#!/usr/bin/env bash
# GENERATED by agentcrew. Edit team.config.yaml + run \`agentcrew sync\`.
# dev: ${dev}
set -euo pipefail
ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")/../.." && pwd)"
SESSION="${prefix}-teamlead"

tmux has-session -t "$SESSION" 2>/dev/null && { tmux attach -t "$SESSION"; exit 0; }

tmux new-session -d -s "$SESSION" -c "$ROOT"
tmux send-keys -t "$SESSION" "claude" Enter

for i in $(seq 1 30); do
  if tmux capture-pane -p -t "$SESSION" | grep -qE "(Welcome to Claude Code|│ >|Try )"; then break; fi
  sleep 1
done

tmux send-keys -t "$SESSION" C-u
sleep 1
tmux send-keys -t "$SESSION" '${bootstrap.replace(/'/g, "'\\''")}' Enter
sleep 3
tmux send-keys -t "$SESSION" Enter
tmux attach -t "$SESSION"
`;

  const doctor = `#!/usr/bin/env bash
# GENERATED by agentcrew.
ok=0
chk() { if eval "$2"; then echo "  ok  $1"; else echo "  !!  $1"; ok=1; fi; }
echo "agentcrew doctor — ${prefix}"
chk "tmux installed"            "command -v tmux >/dev/null"
chk "${pm} installed"           "command -v ${pm} >/dev/null"
chk "port ${port} free"         "! (command -v lsof >/dev/null && lsof -iTCP:${port} -sTCP:LISTEN >/dev/null 2>&1)"
chk ".inbox/ present"           "test -d .agent-crew/.inbox"
chk "health url reachable opt"  "true"  # ${health} checked at launch, not preconditions
exit $ok
`;

  const ensureRole = `#!/usr/bin/env bash
# GENERATED by agentcrew. Idempotently bring up a worker tmux session.
# Usage: ensure-role.sh <role>
set -euo pipefail
ROLE="\${1:?usage: ensure-role.sh <role>}"
ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")/../.." && pwd)"
SESSION="${prefix}-$ROLE"
tmux has-session -t "$SESSION" 2>/dev/null && exit 0
tmux new-session -d -s "$SESSION" -c "$ROOT"
tmux send-keys -t "$SESSION" "claude" Enter
for i in $(seq 1 30); do
  if tmux capture-pane -p -t "$SESSION" | grep -qE "(Welcome to Claude Code|│ >|Try )"; then break; fi
  sleep 1
done
echo "$SESSION up"
`;

  return { "launch.sh": launch, "doctor.sh": doctor, "ensure-role.sh": ensureRole };
}
